### ISSUE TITLE
Plasma Predicate

### ISSUE THREAD

**Issue by tkmct** [cryptoeconomicslab/ovm-contracts#3]
Write Plasma Predicate

**Comment by syuhei176** [comment]
Related to
https://github.com/cryptoeconomicslab/plasma-rust-framework/issues/162#issuecomment-522227613
https://github.com/plasma-group/ovm/issues/1

**Comment by syuhei176** [comment]
Related to https://github.com/cryptoeconomicslab/ovm-contracts/issues/17.

For example we can't do like this.

```
function aaa(Property memory property) {
}
```

But we can write like below.

```
function aaa(bytes property_bytes) {
  let (address predicate, bytes memory input) = abi.decode(property_bytes, (address, bytes));
  let property = Property({predicate: predicate, input: input});
}
```
