### ISSUE TITLE
Naming messes ;(

### ISSUE THREAD

**Issue by shogochiai** [cryptoeconomicslab/ovm-contracts#88]
https://github.com/cryptoeconomicslab/ovm-contracts/blob/master/contracts/UniversalAdjudicationContract.sol#L28

`game`, `property`, and `claim` are very equivalent entities but slightly different nuance there would be I can guess... But it's so confusing for me for now... Any better refactoring?

**Comment by syuhei176** [comment]
`game` is different things, `game` is instance of ChallengeGame. https://github.com/cryptoeconomicslab/ovm-contracts/blob/master/contracts/DataTypes.sol#L13

And it has property.

And we use claim as verb. So at least I will change `_claim` to `_property`.

**Comment by shogochiai** [comment]
`gameId` is generated from `getPropertyId(property)`, and it has `keccak256(abi.encode(property))` has its logic.

Meanwhile, game is acutally: 
```
struct ChallengeGame {
    Property property;
    bytes32[] challenges;
    Decision decision;
    uint256 createdBlock;
}
```
Making its ID via `property` only is somehow able to cause conflict of ID, isn't it?

If so `gameId = getGameId(challengeGame)` and `keccak256(abi.encode(challengeGame))` is much better design maybe?

**Comment by syuhei176** [comment]
game id must be hash of Property because. `challenges`, `decision` and `createdBlock` are status of a game, only property identifies the game.

**Comment by shogochiai** [comment]
I see, then how about putting a nonce field? As long as game for a property won't conflict by design, we don't need nonce though.

**Comment by shogochiai** [comment]
As my recap: We claim a property of checkpoint, exit, and so on. It's encoded hash is called `gameId` but those are not forming `ChallengeGame` yet. (We have to take care this part)

Once a counterclaim has been done of a "claimed property", then that is to be `ChallengeGame` instance, yay 👏 

This `ChallengeGame` has the same property as it has been had and so it's `gameId` has to be the same before-and-after the counterclaim has been done.

Hence, `gameId = getPropertyId(_claim)` is kinda understandable naming for me now.
